name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]  # [macos-latest, ubuntu-latest, windows-latest]
        python: ['3.7', '3.8', '3.9', 'pypy-3.9']  # Nose fails on Python 3.10+
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - run: pip install --upgrade pip
      - run: pip install tox
      - run: tox -e py
